### ISSUE TITLE
Slate bugs in current version of chrome (105+) 

### ISSUE THREAD

**Issue by elbotho** [edtr-io/edtr-io#397]
upsteam issues:
- https://github.com/ianstormtaylor/slate/issues/5119
- https://github.com/ianstormtaylor/slate/issues/5110

**Comment by elbotho** [comment]
CSS solution:
``` css
div[data-slate-editor] {
    -webkit-user-modify: read-write !important;
}
```
package solution:
```
  "resolutions": {
    "slate-dev-environment": "0.1.4"
  },
```

Serlo-Frontend will use the css solution as a quickfix. Edtr should probably consider the second solution
